### ISSUE TITLE
Left + right arrow buttons page through Celine's piece

### ISSUE THREAD

**Issue by bennlich** [hyphacoop/two.compost.digital#42] opened 2021-09-17 20:44 UTC
I just noticed that clicking on the left and right arrow buttons at the bottom of Celine's piece pages through the different sections of the piece. Not sure if this is intentional.

cc @benhylau @s-kennedy @uditvira

**Comment by benhylau** [comment] 2021-09-17 22:09
Really? Doesn't do that for me.

**Comment by bennlich** [comment] 2021-09-18 08:08
Ya. Here are the steps that repro for me:

1) go to https://two.compost.digital/logging-off/001/
2) click the "read the discussion" button
3) scroll down and click the forward arrow

**Comment by uditvira** [comment] 2021-09-18 20:07
Yes confirmed, I see this error too. @s-kennedy any ideas?

**Comment by uditvira** [comment] 2021-09-21 00:30
looks like this is fixed in #60, closing issue

**Closed by uditvira** 2021-09-21 00:30 UTC
Labels: bug
